name: landcover
dependencies:
  - python>=3.11
  - gdal
  - pip
  - pip:
    - torchgeo>=0.6.0
    - torch>=2.0
    - torchvision
    - segmentation-models-pytorch>=0.4.0
    - lightning>=2.0
    - kornia>=0.7.0
    - tensorboard>=2.14
    - einops
    - matplotlib
    - rasterio
    - tqdm